export const MODULES = {
  free: [
    {
      id: 'bant',
      name: 'Qualification BANT',
      icon: '📊',
      category: 'Analyse',
      description: 'Scorez vos prospects en 30 secondes',
      color: 'from-indigo-500 to-purple-500',
      fields: [
        { name: 'prenom', label: 'Prénom', type: 'text', placeholder: 'Jean', required: true },
        { name: 'nom', label: 'Nom', type: 'text', placeholder: 'Dupont', required: true },
        { name: 'fonction', label: 'Fonction', type: 'text', placeholder: 'CEO' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'employes', label: 'Nombre employés', type: 'text', placeholder: '50' },
        { name: 'secteur', label: 'Secteur', type: 'text', placeholder: 'Tech / SaaS' },
        { name: 'budget', label: 'Budget estimé', type: 'text', placeholder: '50k€' },
        { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Contexte...' },
      ],
    },
    {
      id: 'email',
      name: 'Générateur Emails',
      icon: '📧',
      category: 'Communication',
      description: 'Créez des emails percutants en 1 clic',
      color: 'from-emerald-500 to-teal-500',
      fields: [
        { name: 'prenom', label: 'Prénom destinataire', type: 'text', placeholder: 'Marie', required: true },
        { name: 'nom', label: 'Nom destinataire', type: 'text', placeholder: 'Martin' },
        { name: 'fonction', label: 'Fonction', type: 'text', placeholder: 'Head of Sales' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'ScaleUp', required: true },
        { name: 'votre_nom', label: 'Votre nom', type: 'text', placeholder: 'Votre prénom' },
        { name: 'votre_entreprise', label: 'Votre entreprise', type: 'text', placeholder: 'Votre boîte' },
        { name: 'objectif', label: 'Objectif', type: 'select', options: [
          { value: 'intro', label: 'Premier contact' },
          { value: 'demo', label: 'Demander une démo' },
          { value: 'follow', label: 'Suivi' },
          { value: 'relance', label: 'Relance' },
        ]},
        { name: 'ton', label: 'Ton', type: 'select', options: [
          { value: 'pro', label: 'Professionnel' },
          { value: 'cool', label: 'Décontracté' },
          { value: 'formel', label: 'Formel' },
        ]},
      ],
    },
  ],
  premium: [
    {
      id: 'linkedin',
      name: 'Recherche LinkedIn',
      icon: '💼',
      category: 'Enrichissement',
      description: 'Trouvez automatiquement le profil LinkedIn',
      color: 'from-blue-500 to-cyan-500',
      fields: [
        { name: 'prenom', label: 'Prénom', type: 'text', placeholder: 'Jean', required: true },
        { name: 'nom', label: 'Nom', type: 'text', placeholder: 'Dupont' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'fonction', label: 'Fonction', type: 'text', placeholder: 'CEO' },
      ],
    },
    {
      id: 'company',
      name: 'Veille Entreprise',
      icon: '🏢',
      category: 'Enrichissement',
      description: 'Analysez automatiquement une entreprise',
      color: 'from-orange-500 to-red-500',
      fields: [
        { name: 'entreprise', label: 'Nom entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'site', label: 'Site web', type: 'text', placeholder: 'techcorp.com' },
      ],
    },
    {
      id: 'script',
      name: 'Script Appel',
      icon: '📞',
      category: 'Communication',
      description: 'Générez un script pour cold call',
      color: 'from-purple-500 to-pink-500',
      fields: [
        { name: 'prenom', label: 'Prénom prospect', type: 'text', placeholder: 'Jean', required: true },
        { name: 'fonction', label: 'Fonction', type: 'text', placeholder: 'Head of Sales' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp' },
        { name: 'produit', label: 'Votre produit', type: 'text', placeholder: 'Outil prospection IA' },
        { name: 'duree', label: 'Durée appel', type: 'select', options: [
          { value: '2', label: '2 min (gatekeeper)' },
          { value: '5', label: '5 min (decision maker)' },
          { value: '15', label: '15 min (discovery)' },
        ]},
      ],
    },
    {
      id: 'sequence',
      name: 'Séquence Email',
      icon: '📬',
      category: 'Communication',
      description: 'Générez 5 emails de suivi automatiques',
      color: 'from-green-500 to-emerald-500',
      fields: [
        { name: 'prenom', label: 'Prénom', type: 'text', placeholder: 'Marie', required: true },
        { name: 'nom', label: 'Nom', type: 'text', placeholder: 'Martin' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'ScaleUp' },
        { name: 'objectif', label: 'Objectif', type: 'text', placeholder: 'Obtenir un RDV démo' },
      ],
    },
    {
      id: 'objection',
      name: 'Réponses Objections',
      icon: '💬',
      category: 'Closing',
      description: 'Réponses aux objections avec techniques closing',
      color: 'from-rose-500 to-red-500',
      fields: [
        { name: 'objection', label: 'Type objection', type: 'select', options: [
          { value: 'prix', label: '💰 C\'est trop cher' },
          { value: 'timing', label: '⏰ Pas le bon moment' },
          { value: 'conc', label: '🏆 Concurrent' },
          { value: 'budget', label: '📊 Pas de budget' },
          { value: 'interne', label: '👥 Doit parler équipe' },
          { value: 'besoin', label: '🎯 Pas intérêt' },
          { value: 'refus', label: '🚫 On ne veut pas' },
        ]},
        { name: 'contexte', label: 'Contexte', type: 'textarea', placeholder: 'SaaS 79€/mois...' },
      ],
    },
    {
      id: 'roi',
      name: 'Calculateur ROI',
      icon: '💰',
      category: 'Closing',
      description: 'Calculez et présentez le ROI',
      color: 'from-yellow-500 to-amber-500',
      fields: [
        { name: 'nb_commerciaux', label: 'Nb commerciaux', type: 'text', placeholder: '5' },
        { name: 'temps_qualif', label: 'Min/lead', type: 'text', placeholder: '30' },
        { name: 'nb_leads', label: 'Leads/mois', type: 'text', placeholder: '200' },
        { name: 'salaire', label: 'Salaire (€)', type: 'text', placeholder: '45000' },
        { name: 'prix_solution', label: 'Prix/mois', type: 'text', placeholder: '79' },
      ],
    },
    {
      id: 'crm',
      name: 'Fiche CRM',
      icon: '📋',
      category: 'Organisation',
      description: 'Générez une fiche Notion-ready',
      color: 'from-violet-500 to-purple-500',
      fields: [
        { name: 'prenom', label: 'Prénom', type: 'text', placeholder: 'Jean', required: true },
        { name: 'nom', label: 'Nom', type: 'text', placeholder: 'Dupont' },
        { name: 'fonction', label: 'Fonction', type: 'text', placeholder: 'CEO' },
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'email', label: 'Email', type: 'text', placeholder: 'jean@techcorp.com' },
        { name: 'tel', label: 'Téléphone', type: 'text', placeholder: '+33 6 12 34 56 78' },
        { name: 'source', label: 'Source', type: 'select', options: [
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'cold_email', label: 'Cold Email' },
          { value: 'referral', label: 'Recommandation' },
          { value: 'website', label: 'Site web' },
          { value: 'event', label: 'Événement' },
        ]},
        { name: 'statut', label: 'Statut', type: 'select', options: [
          { value: 'new', label: '🔵 Prospect' },
          { value: 'qualified', label: '🟡 Qualifié' },
          { value: 'demo', label: '🟠 Démo' },
          { value: 'proposal', label: '🟠 Proposition' },
          { value: 'negotiation', label: '🟠 Négociation' },
          { value: 'won', label: '🟢 Gagné' },
          { value: 'lost', label: '🔴 Perdu' },
        ]},
        { name: 'notes', label: 'Notes', type: 'textarea', placeholder: 'Échange du 15/04...' },
      ],
    },
    {
      id: 'deal',
      name: 'Prédiction Deal',
      icon: '🎯',
      category: 'Analyse',
      description: 'Prédisez si un deal va se close',
      color: 'from-cyan-500 to-blue-500',
      fields: [
        { name: 'score_bant', label: 'Score BANT (0-100)', type: 'text', placeholder: '75' },
        { name: 'nb_reunions', label: 'Réunions', type: 'text', placeholder: '3' },
        { name: 'stakeholder', label: 'Stakeholders', type: 'text', placeholder: '2' },
        { name: 'concurrents', label: 'Concurrents', type: 'select', options: [
          { value: '0', label: 'Aucun' },
          { value: '1', label: '1 concurrent' },
          { value: '2-3', label: '2-3 concurrents' },
          { value: '4+', label: '4+ concurrents' },
        ]},
        { name: 'proposal', label: 'Proposition', type: 'select', options: [
          { value: 'oui', label: 'Oui' },
          { value: 'non', label: 'Non' },
          { value: 'en_cours', label: 'En cours' },
        ]},
        { name: 'temps_cycle', label: 'Semaines cycle', type: 'text', placeholder: '6' },
      ],
    },
    {
      id: 'competitor',
      name: 'Analyse Concurrent',
      icon: '⚔️',
      category: 'Analyse',
      description: 'Comparez-vous aux concurrents',
      color: 'from-red-500 to-orange-500',
      fields: [
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'concurrent', label: 'Concurrent', type: 'text', placeholder: 'HubSpot' },
        { name: 'votre_produit', label: 'Votre produit', type: 'text', placeholder: 'LeadFlow IA' },
      ],
    },
    {
      id: 'proposal',
      name: 'Proposition Commerciale',
      icon: '📄',
      category: 'Closing',
      description: 'Générez une proposition complète',
      color: 'from-teal-500 to-cyan-500',
      fields: [
        { name: 'entreprise', label: 'Entreprise', type: 'text', placeholder: 'TechCorp', required: true },
        { name: 'contact', label: 'Contact', type: 'text', placeholder: 'Jean Dupont, CEO' },
        { name: 'besoin', label: 'Besoin', type: 'textarea', placeholder: 'Automatiser qualification...' },
        { name: 'solution', label: 'Solution', type: 'text', placeholder: 'LeadFlow IA Pro' },
        { name: 'prix', label: 'Prix (€)', type: 'text', placeholder: '948' },
        { name: 'validite', label: 'Validité (jours)', type: 'text', placeholder: '30' },
      ],
    },
  ]
}

export const PLANS = {
  free: {
    name: 'Gratuit',
    price: 0,
    requests: 5,
    modules: ['bant', 'email'],
  },
  pro: {
    name: 'Professionnel',
    price: 4900,
    requests: 200,
    modules: ['bant', 'email', 'linkedin', 'company', 'script', 'sequence', 'objection', 'roi', 'crm', 'deal'],
  },
  agency: {
    name: 'Agency',
    price: 14900,
    requests: 1000,
    modules: ['bant', 'email', 'linkedin', 'company', 'script', 'sequence', 'objection', 'roi', 'crm', 'deal', 'competitor', 'proposal'],
  }
}

export const getAllModules = () => [...MODULES.free, ...MODULES.premium]
export const getModuleById = (id) => getAllModules().find(m => m.id === id)